#### Introduction to Data Science
- any information existed in a file
- it may be either meaningful or meaningless
- raw data:extract the data(data mining)
- Types of data in our device
    - .txt,.doc,.xls,.ppt,.jpg,.png,.mp3,.mp4 etc...
    - images/(text),mp3,mp4
- Types of data used in realtime
- 2types 
    1. Quantative and
    2. Qualitative
    1. **Quantitative**
        1. Discrete
            - this type of data is fixed/constant
                - numbers on die(varies from 1 to 6)
                - distance,color,nationality,size etc.
        2. Continuous
            - data is continuous in nature
            - height,weight,time in hours
    2. **Qualitative**
        - quality(data is catogerized and placed in terms of category)
        - data submission in forms
- Types of data in statistics
    - 4 types
        1. nominal,ordinal,interval and rational
            - Nominal data : data depends/categorized based on names
            - Ordinal :data is placed based on the order of data points
            - interval:data present in a range
            - rational : p/q:data is meaningfully either added or subracted or multiplied or divided(ratio)
- **Data Science**
    - The complete study of data is called science
    - data analysis,machine learning,Artificial Intelligence are a part of data science

### Modules
- set/collection/group of statements called as function
- collection of functions said to be a module
- collection of modules said to be package

In [1]:
9+45

54

In [2]:
import math

In [3]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [4]:
help(math.sin)

Help on built-in function sin in module math:

sin(x, /)
    Return the sine of x (measured in radians).



In [5]:
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



In [6]:
help(math.gcd)

Help on built-in function gcd in module math:

gcd(*integers)
    Greatest Common Divisor.



In [7]:
for ch in 4*"r": # * multiple
    print(ch)

r
r
r
r


In [8]:
math.gcd(27,4)

1

In [12]:
math.gcd(90,76)

2

In [13]:
math.sqrt(144)

12.0

In [15]:
math.sqrt(99)

9.9498743710662

In [17]:
math.sqrt(2)

1.4142135623730951

In [18]:
int(math.sqrt(2))

1

In [19]:
math.factorial(7)

5040

#### random module
- used to generate random values/numbers/samples

In [20]:
import random

In [21]:
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_accumulate',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_floor',
 '_inst',
 '_log',
 '_os',
 '_pi',
 '_random',
 '_repeat',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randbytes',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [22]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [26]:
random.randint(10,45)

13

In [27]:
help(random.random)

Help on built-in function random:

random() method of random.Random instance
    random() -> x in the interval [0, 1).



In [30]:
random.random()

0.3529206273687041

#### Modules in Data Science
- Numpy
- Scipy
- scikit learn(sklean)
- pandas
- matplotlib
- seaborn etc.

#### Numpy
- Numpy stands for Numerical Python one of the most important data science modules
- it is used to deal with array type of data
- used to gather data 
- each row in the array/matrix called as a sample
- Mainly used for Scientific computation
- **Installation**
    - install the module in your local machine(IDLE) as a platform
        - pip install module(numpy) in your cmd
    - importing the module at your workspace
        - import the module

In [31]:
import numpy as np 
# as means alias np is the var represents the numpy module

In [32]:
import numpy as r

In [33]:
import numpy

In [34]:
np.__version__

'1.21.5'

In [35]:
r.__version__

'1.21.5'

In [36]:
numpy.__version__

'1.21.5'

In [37]:
dir(r)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


#### arrays
- array is an homogenous data structure stores one type of data at a time
- numpy.array() used to declare the array/matrix
- we have 32 dimensional arrays to store the data
- 1,2d(row,col)
- it is immutable in nature

In [38]:
print(numpy.array([1,2,3,4,5]))

[1 2 3 4 5]


In [39]:
[4,5,'hi',90.34]

[4, 5, 'hi', 90.34]

In [40]:
print(numpy.array([3,'e',10]))

['3' 'e' '10']


In [41]:
ar=np.array((3,4,5,6,10))
print(ar)

[ 3  4  5  6 10]


In [44]:
print(np.array(range(10,34)))
print("............")
print(np.array(range(10,200,6)))
# row matrix

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
............
[ 10  16  22  28  34  40  46  52  58  64  70  76  82  88  94 100 106 112
 118 124 130 136 142 148 154 160 166 172 178 184 190 196]


In [45]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [48]:
ar=np.array(range(10,25),dtype=float)
print(ar)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.]


In [51]:
print(np.array([3,4,5,6,4,],dtype="str",ndmin=3))

[[['3' '4' '5' '6' '4']]]


In [52]:
# 2d arrays
ar2=np.array([[2,3,4],[4,5,6]])
print(ar2) # 2x3

[[2 3 4]
 [4 5 6]]


In [53]:
ar2.ndim # dimensions of array

2

In [54]:
ar2.shape # row,col

(2, 3)

In [55]:
ar2.size # no.of 

6

In [56]:
ar2.itemsize # size allocated in the memory to each point

4

In [57]:
mul=np.array([[[1,2,3],[4,5,6]],[[10,11,12],[13,14,15]]])
print(mul)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]


In [58]:
mul.ndim

3

In [62]:
print(np.array(range(1,10),ndmin=32))

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5 6
                                7 8 9]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


#### functions support to create arrays
1. arange
2. linspace
3. eye/identity
4. zeros
5. ones
6. full
7. fill
8. diag
9. random
10. reshape(in numpy)

In [66]:
o=np.ones(5,dtype=int)
print(o)
o2=np.ones((4,5))
o2

[1 1 1 1 1]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
z=np.zeros(10)
print(z)
z2=np.zeros((3,3))
z2

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# full and fill
f=np.full(4,9) # (size,ele)
print(f)
f2=np.full((3,4),'a')
f2

[9 9 9 9]


array([['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a']], dtype='<U1')

In [77]:
ar2.fill(9) # existed array gets modified with 9
ar2

array([[9, 9, 9],
       [9, 9, 9]])

In [79]:
f2.fill('new')
f2

array([['n', 'n', 'n', 'n'],
       ['n', 'n', 'n', 'n'],
       ['n', 'n', 'n', 'n']], dtype='<U1')

In [80]:
#you can create the diagnal matrix
# you can get the diagnal values in existed array

In [81]:
mul

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [82]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [85]:
np.diag([3,4,5,6])

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [87]:
ml=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ml)
np.diag(ml)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [95]:
print(np.arange(15)) # it works similar to range()
print("...........")
print(np.arange(10,50))
print("..........")
print(np.arange(100,300,9))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
...........
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
..........
[100 109 118 127 136 145 154 163 172 181 190 199 208 217 226 235 244 253
 262 271 280 289 298]


In [96]:
#reshape the existed one
arn=np.arange(10,25)
print(arn) # row matrix

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [97]:
arn.reshape(3,5)
# (15,1),(3,5),(5,3),(1,15)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [99]:
arn.reshape(5,3) # 5 rows with 3 columns

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [102]:
# while reshaping the existed array
new=np.arange(1000,2000).reshape(25,-3)
print(new)

[[1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013
  1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027
  1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039]
 [1040 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053
  1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067
  1068 1069 1070 1071 1072 1073 1074 1075 1076 1077 1078 1079]
 [1080 1081 1082 1083 1084 1085 1086 1087 1088 1089 1090 1091 1092 1093
  1094 1095 1096 1097 1098 1099 1100 1101 1102 1103 1104 1105 1106 1107
  1108 1109 1110 1111 1112 1113 1114 1115 1116 1117 1118 1119]
 [1120 1121 1122 1123 1124 1125 1126 1127 1128 1129 1130 1131 1132 1133
  1134 1135 1136 1137 1138 1139 1140 1141 1142 1143 1144 1145 1146 1147
  1148 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159]
 [1160 1161 1162 1163 1164 1165 1166 1167 1168 1169 1170 1171 1172 1173
  1174 1175 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187
  1188 1189 1190 1191 1192 1

In [101]:
1000/25

40.0

In [104]:
new.ndim

2