#### Today Topics
- continued with numpy
- pandas

### linspace
   - linear space which equally patition the given interval 
        [0,1)
   - by default it will give us 50 equal partitions
                                                                      
   - numpy.linspace(start,stop,n(optional))
### random
- random is the submodule in numpy which generates random integers/samples
- np.random.randint()
- np.random.randint(start,stop)
- np.random.randint(start,stop,n)
- np.random.random(row,col)
    - within the interval [0,1)
- np.random.rand()
- np.random.randn()

In [2]:
import numpy as np

In [3]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [4]:
ln=np.linspace(200,500) # both limits are inclusive
print(ln)

[200.         206.12244898 212.24489796 218.36734694 224.48979592
 230.6122449  236.73469388 242.85714286 248.97959184 255.10204082
 261.2244898  267.34693878 273.46938776 279.59183673 285.71428571
 291.83673469 297.95918367 304.08163265 310.20408163 316.32653061
 322.44897959 328.57142857 334.69387755 340.81632653 346.93877551
 353.06122449 359.18367347 365.30612245 371.42857143 377.55102041
 383.67346939 389.79591837 395.91836735 402.04081633 408.16326531
 414.28571429 420.40816327 426.53061224 432.65306122 438.7755102
 444.89795918 451.02040816 457.14285714 463.26530612 469.3877551
 475.51020408 481.63265306 487.75510204 493.87755102 500.        ]


In [6]:
print(*range(10))

0 1 2 3 4 5 6 7 8 9


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(np.linspace(300,1000,30))

[ 300.          324.13793103  348.27586207  372.4137931   396.55172414
  420.68965517  444.82758621  468.96551724  493.10344828  517.24137931
  541.37931034  565.51724138  589.65517241  613.79310345  637.93103448
  662.06896552  686.20689655  710.34482759  734.48275862  758.62068966
  782.75862069  806.89655172  831.03448276  855.17241379  879.31034483
  903.44827586  927.5862069   951.72413793  975.86206897 1000.        ]


In [9]:
print(np.linspace(300,1000,100))
#write a python logic to print only even integers

[ 300.          307.07070707  314.14141414  321.21212121  328.28282828
  335.35353535  342.42424242  349.49494949  356.56565657  363.63636364
  370.70707071  377.77777778  384.84848485  391.91919192  398.98989899
  406.06060606  413.13131313  420.2020202   427.27272727  434.34343434
  441.41414141  448.48484848  455.55555556  462.62626263  469.6969697
  476.76767677  483.83838384  490.90909091  497.97979798  505.05050505
  512.12121212  519.19191919  526.26262626  533.33333333  540.4040404
  547.47474747  554.54545455  561.61616162  568.68686869  575.75757576
  582.82828283  589.8989899   596.96969697  604.04040404  611.11111111
  618.18181818  625.25252525  632.32323232  639.39393939  646.46464646
  653.53535354  660.60606061  667.67676768  674.74747475  681.81818182
  688.88888889  695.95959596  703.03030303  710.1010101   717.17171717
  724.24242424  731.31313131  738.38383838  745.45454545  752.52525253
  759.5959596   766.66666667  773.73737374  780.80808081  787.87878788
  794.94

In [10]:
#### random

In [13]:
np.random.randint(100) 
# it will generate a random integer b/w 0 and n

67

In [22]:
print(np.random.randint(100,1000)) # single random integer
#generating n random integers
rn=np.random.randint(int(input()),int(input()),25).reshape(5,5)
print(rn)


# row matrix convert this into 2d array with equal size

984
3000
4000
[[3573 3726 3843 3980 3531]
 [3590 3736 3097 3371 3163]
 [3968 3109 3000 3221 3776]
 [3292 3530 3734 3397 3029]
 [3753 3989 3575 3563 3833]]


In [21]:
print(np.random.randint(1000,40000,25).reshape(5,-3))

[[ 3461  3281 28709 22783 11663]
 [38562 33661 21831 37226  5676]
 [ 5795 10047 20149 17655 10153]
 [18919  4430 22424 16402 27350]
 [27093 23455 21976 26871  1686]]


In [26]:
np.random.random() # b/w [0,1)

0.5260333542734554

In [29]:
np.random.random((2,5))

array([[0.77581556, 0.5399049 , 0.96823509, 0.2234442 , 0.99357832],
       [0.12939018, 0.80272305, 0.14947903, 0.91888218, 0.36320155]])

In [31]:
np.random.random(9).reshape(3,3)

array([[0.38197328, 0.96294616, 0.01475959],
       [0.20610634, 0.90133153, 0.88247368],
       [0.13419582, 0.29329418, 0.37197716]])

In [34]:
np.random.rand()

0.03470280772635492

In [36]:
np.random.rand(6)

array([0.91371499, 0.18324795, 0.79404467, 0.2891643 , 0.30629999,
       0.90668788])

In [39]:
np.random.rand(5,5)

array([[0.17553207, 0.83906057, 0.84080776, 0.87704939, 0.41449664],
       [0.80374508, 0.50133983, 0.8885459 , 0.58402407, 0.51904353],
       [0.37281337, 0.75958972, 0.64500887, 0.38288167, 0.13246433],
       [0.18472405, 0.78034459, 0.71869391, 0.78752306, 0.19879146],
       [0.36844339, 0.16950812, 0.24647339, 0.97176844, 0.50098488]])

In [43]:
np.random.randn() # [-ve,+ve)


-1.0694979213299454

In [44]:
np.random.randn(3)

array([ 1.09861797, -2.01433559, -0.55338338])

In [45]:
np.random.randn(3,5)

array([[ 0.56459088,  0.80643587,  0.70038115,  0.32645736, -0.4643658 ],
       [-0.21621161,  0.02465654, -0.39869847, -0.31727807,  0.29512721],
       [ 1.24857468,  1.1329785 , -1.127548  ,  0.7377569 ,  0.67894953]])

#### array indexing and slicing
- index is of 3 types
    1. +ve indexing
        - 0 to len(iterable)-1
    2. -ve indexing
        - -1 to -infinite
    3. fancy indexing
        - condition as index

In [46]:
rn #

array([[3573, 3726, 3843, 3980, 3531],
       [3590, 3736, 3097, 3371, 3163],
       [3968, 3109, 3000, 3221, 3776],
       [3292, 3530, 3734, 3397, 3029],
       [3753, 3989, 3575, 3563, 3833]])

In [47]:
rn[2]# 3rd row

array([3968, 3109, 3000, 3221, 3776])

In [48]:
rn[-2] # lat but one row/2nd row from last

array([3292, 3530, 3734, 3397, 3029])

In [50]:
#specific value
rn[2][2]

3000

In [51]:
rn[:,2:] # columns from 3rd index in entire rows

array([[3843, 3980, 3531],
       [3097, 3371, 3163],
       [3000, 3221, 3776],
       [3734, 3397, 3029],
       [3575, 3563, 3833]])

In [52]:
rn[:]

array([[3573, 3726, 3843, 3980, 3531],
       [3590, 3736, 3097, 3371, 3163],
       [3968, 3109, 3000, 3221, 3776],
       [3292, 3530, 3734, 3397, 3029],
       [3753, 3989, 3575, 3563, 3833]])

In [53]:
rn[::]

array([[3573, 3726, 3843, 3980, 3531],
       [3590, 3736, 3097, 3371, 3163],
       [3968, 3109, 3000, 3221, 3776],
       [3292, 3530, 3734, 3397, 3029],
       [3753, 3989, 3575, 3563, 3833]])

In [54]:
rn[::-1]# from last to first rows

array([[3753, 3989, 3575, 3563, 3833],
       [3292, 3530, 3734, 3397, 3029],
       [3968, 3109, 3000, 3221, 3776],
       [3590, 3736, 3097, 3371, 3163],
       [3573, 3726, 3843, 3980, 3531]])

In [55]:
name="iiit"
name[::-1]

'tiii'

In [56]:
rn.transpose()

array([[3573, 3590, 3968, 3292, 3753],
       [3726, 3736, 3109, 3530, 3989],
       [3843, 3097, 3000, 3734, 3575],
       [3980, 3371, 3221, 3397, 3563],
       [3531, 3163, 3776, 3029, 3833]])

In [57]:
help(rn.transpose)

Help on built-in function transpose:

transpose(...) method of numpy.ndarray instance
    a.transpose(*axes)
    
    Returns a view of the array with axes transposed.
    
    For a 1-D array this has no effect, as a transposed vector is simply the
    same vector. To convert a 1-D array into a 2D column vector, an additional
    dimension must be added. `np.atleast2d(a).T` achieves this, as does
    `a[:, np.newaxis]`.
    For a 2-D array, this is a standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided and
    ``a.shape = (i[0], i[1], ... i[n-2], i[n-1])``, then
    ``a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0])``.
    
    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints
    
     * None or no argument: reverses the order of the axes.
    
     * tuple of ints: `i` in the `j`-th place in the tuple means `a`'s
       `i`-th axis becomes `a.transpos

In [58]:
rn

array([[3573, 3726, 3843, 3980, 3531],
       [3590, 3736, 3097, 3371, 3163],
       [3968, 3109, 3000, 3221, 3776],
       [3292, 3530, 3734, 3397, 3029],
       [3753, 3989, 3575, 3563, 3833]])

In [59]:
rn[::2] # alternate rows

array([[3573, 3726, 3843, 3980, 3531],
       [3968, 3109, 3000, 3221, 3776],
       [3753, 3989, 3575, 3563, 3833]])

In [60]:
# alternate cols in alternate rows
rn[::2,::2]

array([[3573, 3843, 3531],
       [3968, 3000, 3776],
       [3753, 3575, 3833]])

#### Scientific computation


In [61]:
# create 2 equal sizes 2d arrays

In [62]:
man=np.arange(45).reshape(3,3,5) 
print(man)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [65]:
man[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
man[1][:,2:4]

array([[17, 18],
       [22, 23],
       [27, 28]])

In [67]:
#fancy indexing

In [69]:
rn

array([[3573, 3726, 3843, 3980, 3531],
       [3590, 3736, 3097, 3371, 3163],
       [3968, 3109, 3000, 3221, 3776],
       [3292, 3530, 3734, 3397, 3029],
       [3753, 3989, 3575, 3563, 3833]])

In [70]:
# value>3000 to 3700
#val<3500
rn[:3]

array([[3573, 3726, 3843, 3980, 3531],
       [3590, 3736, 3097, 3371, 3163],
       [3968, 3109, 3000, 3221, 3776]])

In [73]:
rn>3500

array([[ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [ True, False, False, False,  True],
       [False,  True,  True, False, False],
       [ True,  True,  True,  True,  True]])

In [78]:
(rn>3000) or (rn<3700)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [80]:
rn[rn>3500] # pass the condition as index

array([3573, 3726, 3843, 3980, 3531, 3590, 3736, 3968, 3776, 3530, 3734,
       3753, 3989, 3575, 3563, 3833])

In [81]:
# scientific computation

In [82]:
man=np.arange(25).reshape(5,5)
new=np.random.randint(100,500,25).reshape(5,5)
print(man)
print(new)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[214 394 237 275 411]
 [233 385 394 305 296]
 [208 182 215 144 263]
 [403 173 204 446 277]
 [487 460 491 234 480]]


In [83]:
# perform all the arithmetic op'ns
# +,-,/,*,**,%
print(new+man)
print(new-man)
print(new*man)
print(new/man)
print(new//man)
print(new**man)
print(new%man)

[[214 395 239 278 415]
 [238 391 401 313 305]
 [218 193 227 157 277]
 [418 189 221 464 296]
 [507 481 513 257 504]]
[[214 393 235 272 407]
 [228 379 387 297 287]
 [198 171 203 131 249]
 [388 157 187 428 258]
 [467 439 469 211 456]]
[[    0   394   474   825  1644]
 [ 1165  2310  2758  2440  2664]
 [ 2080  2002  2580  1872  3682]
 [ 6045  2768  3468  8028  5263]
 [ 9740  9660 10802  5382 11520]]
[[         inf 394.         118.5         91.66666667 102.75      ]
 [ 46.6         64.16666667  56.28571429  38.125       32.88888889]
 [ 20.8         16.54545455  17.91666667  11.07692308  18.78571429]
 [ 26.86666667  10.8125      12.          24.77777778  14.57894737]
 [ 24.35        21.9047619   22.31818182  10.17391304  20.        ]]
[[  0 394 118  91 102]
 [ 46  64  56  38  32]
 [ 20  16  17  11  18]
 [ 26  10  12  24  14]
 [ 24  21  22  10  20]]
[[          1         394       56169    20796875 -1530466831]
 [ -474910967   866240769  2077767296   924059009   671088640]
 [          0  1816

C:\Users\ruthu\AppData\Local\Temp\ipykernel_11096\1103400365.py:6: RuntimeWarning: divide by zero encountered in true_divide
  print(new/man)
C:\Users\ruthu\AppData\Local\Temp\ipykernel_11096\1103400365.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(new//man)
C:\Users\ruthu\AppData\Local\Temp\ipykernel_11096\1103400365.py:9: RuntimeWarning: divide by zero encountered in remainder
  print(new%man)


In [85]:
print(np.dot(new,man))

[[16685 18216 19747 21278 22809]
 [16360 17973 19586 21199 22812]
 [10480 11492 12504 13516 14528]
 [15135 16638 18141 19644 21147]
 [20320 22472 24624 26776 28928]]


In [86]:
print(np.sum(new))

7811


In [88]:
np.min(new)

144

In [90]:
new.min()

144

In [91]:
new.std() # standard deviation of values

108.95726868823392

In [92]:
new.var()

11871.6864

In [93]:
import math

In [94]:
math.sqrt(11871)

108.95411878400927

In [95]:
new.mean()

312.44

In [96]:
#logarithms
#exponentials

In [97]:
np.log(1)

0.0

In [98]:
np.log(10)

2.302585092994046

In [99]:
np.log2(2)

1.0

In [100]:
np.log(new)

array([[5.36597602, 5.97635091, 5.46806014, 5.6167711 , 6.01859321],
       [5.45103845, 5.95324333, 5.97635091, 5.72031178, 5.69035945],
       [5.33753808, 5.20400669, 5.37063803, 4.9698133 , 5.57215403],
       [5.99893656, 5.15329159, 5.31811999, 6.10031895, 5.62401751],
       [6.18826412, 6.13122649, 6.19644413, 5.45532112, 6.1737861 ]])

In [102]:
np.exp(1)

2.718281828459045

In [103]:
np.exp(2)

7.38905609893065

In [104]:
np.exp(new)

array([[8.68998701e+092, 1.29427294e+171, 8.46822154e+102,
        2.69763087e+119, 3.12631016e+178],
       [1.55100888e+101, 1.59725969e+167, 1.29427294e+171,
        2.88281638e+132, 3.55767804e+128],
       [2.15403242e+090, 1.10051434e+079, 2.36218338e+093,
        3.45466066e+062, 1.65748169e+114],
       [1.04876022e+175, 1.35814259e+075, 3.94524800e+088,
        4.95836997e+193, 1.99329459e+120],
       [3.17258077e+211, 5.96295697e+199, 1.73217041e+213,
        4.21607925e+101, 2.89301918e+208]])

In [105]:
#vectorized function in numpy

In [106]:
def greater(a,b):
    if a>b:
        return a
    else:return b
    
greater(20,15)

20

In [108]:
greater(64,100)

100

In [109]:
greater([3,4,10],[10,2,45])
# what should be the output
#[10,4,45]

[10, 2, 45]

In [110]:
greater([13,4,10],[10,2,45])

[13, 4, 10]

In [112]:
g=np.vectorize(greater)
g([3,4,10],[10,2,45])

array([10,  4, 45])

#### pandas
- Pandas means panel data
- data is arranged in the form of rows and columns(panel)
    - tabular data
- used for data analysis,data manipulation and data cleaning
    - analysing the dataset/data frame
    - conversion/merging multiple datasets
    - removal of null data in the dataset
- 2 data structures to represent the data
    1. Series
        - sequential data points arranged either side by side of line by line
    2. Data Frame
        - 2d structure can represent the data in the form of rows and columns

In [113]:
import pandas as pd

In [114]:
pd.__version__

'1.4.4'

In [115]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_ve

In [116]:
#try with str
pd.Series("hello I am Ruthu from APSSDC".split())

0     hello
1         I
2        am
3     Ruthu
4      from
5    APSSDC
dtype: object

In [118]:
#try with tuple
#list
li=[4,5,6,10,45]
pd.Series(li,index=[6,7,8,9,20])

6      4
7      5
8      6
9     10
20    45
dtype: int64

In [121]:

# try with dictionary
dict1={"a":1,"b":2,"c":3}
s=pd.Series(dict1)
s.index=['one','two','three']
s

one      1
two      2
three    3
dtype: int64

In [127]:
dates=pd.date_range("2023-03-01","2023-03-10")
temp=[40,45,39,46,47,48,44,42,43,48]
pd.Series(temp,index=dates)

2023-03-01    40
2023-03-02    45
2023-03-03    39
2023-03-04    46
2023-03-05    47
2023-03-06    48
2023-03-07    44
2023-03-08    42
2023-03-09    43
2023-03-10    48
Freq: D, dtype: int64